config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users' }

  resources :users

  resources :projects do
    resources :tasks
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :task
  mount_uploader :upload, AttachmentUploader
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_error

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  enum status: { 'New': 0, 'Being resolved': 1, 'Waiting for client': 2, 'Done': 3 }

  after_initialize :set_default_status, if: :new_record?

  validates :subject, :status, :user_id, :project_id, presence: true

  private

  # Set default status to 0 (New)
  #
  # @return [void]
  def set_default_status
    self.status ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader  :avatar, AvatarUploader
  has_many :tasks, dependent: :restrict_with_error
  validates :first_name, :last_name, :email, presence: true

  # Returns the full name of the user
  #
  # @return [String]
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  # Configure permitted parameters for devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  # Root path for the application
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    save_project('Project was successfully created.', :new)
  end

  def update
    @project.assign_attributes(project_params)
    save_project('Project was successfully updated.', :edit)
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Saves the project and redirects to the specified path
  def save_project(success_notice, fail_action)
    if @project.save
      redirect_to @project, notice: success_notice
    else
      render fail_action
    end
  end

  # Sets the project for the specified id in the params
  def set_project
    @project = Project.find(params[:id])
  end

  # Defines the permitted parameters for a project
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = @project.tasks.build

    # Allows us to build 3 attachments for each task
    3.times { @task.attachments.build }
  end

  def edit
  end

  def create
    @task = @project.tasks.build(task_params)
    save_task('Task was successfully created.', :new)
  end

  def update
    @task.assign_attributes(task_params)
    save_task('Task was successfully updated.', :edit)
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project), notice: 'Task was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  # Saves the task and redirects to the specified path
  def save_task(success_notice, fail_action)
    if @task.save
      redirect_to project_task_path(@project, @task), notice: success_notice
    else
      render fail_action
    end
  end

  # Permitted parameters for a task
  def task_params
    params.require(:task).permit(:subject, :description, :status, :user_id, attachments_attributes: [:id, :upload, :description, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    save_user('User was successfully created.', :new)
  end


  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    @user.assign_attributes(user_params)
    save_user('User was successfully updated.', :edit)
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private

  # Saves the user and redirects to the specified path
  def save_user(success_notice, fail_action)
    if @user.save
      redirect_to @user, notice: success_notice
    else
      render fail_action
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Defines the permitted parameters for a user
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
.center-div.d-flex.justify-content-center
  %img{ src: '/cute-cat.gif', alt: 'Cat', width: '500px'}

app/views/layouts/application.html.haml
- if user_signed_in?
  !!!
  %html
    %head
      %link{rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"}
      %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"}
      %script{src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"}
      %script{src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"}
      %title Project Manager
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

      = csrf_meta_tags

    %body
      %nav.navbar.py-4.shadow-sm.mb-5.px-5
        %a.h2.text-decoration-none{ href: root_path, style: 'color: black; text-decoration: none;' } Project Manager on Rails
        %ul.nav.d-flex.align-items-center.h6
          %li.nav-item
            = link_to 'Users', users_path, style: 'color: black; text-decoration: none;'
          %li.nav-item.mx-4
            = link_to 'Projects', projects_path, style: 'color: black; text-decoration: none;'
          = button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-btn'

    .px-5
      = yield

- else
  .px-5
    = yield

app/views/layouts/devise.html.haml
!!! 5
%html
  %head
    %link{ rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" }
    %script{ src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" }
  %body
    = yield

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  .form-group
    = f.input :name, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.input :description, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.button :submit, class: 'btn btn-primary'

app/views/projects/edit.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1= 'Edit ' + @project.name
      %a.btn.btn-primary{ href: projects_path } Back
  %div.card-body
    = render 'form'

app/views/projects/index.html.haml
%div.card.mx-5
  %div.card-header
    %h1 Projects
  %div.card-body
    %table.table.table-md
      %thead
        %tr
          %th Name
          %th Date Created
          %th Task Count
          %th Actions
      %tbody
        - @projects.each do |project|
          %tr
            %td= link_to project.name, project_path(project)
            %td= project.created_at.strftime("%d-%m-%Y")
            %td= project.tasks.count
            %td.d-flex
              %a.btn.btn-primary.mr-2{ href: edit_project_path(project) } Edit
              = button_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    - if @projects.total_pages > 1
      .pagination
        = paginate @projects

  %div.card-footer
    %div.d-flex.justify-content-between
      %a.btn.btn-primary{ href: root_path } Back
      %a.btn.btn-success{ href: new_project_path } Add New Project

app/views/projects/new.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1 Add new project
      %a.btn.btn-primary{ href: projects_path } Back
  %div.card-body
    = render 'form'

app/views/projects/show.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between
      %h4= @project.name
      %div.d-flex
        %a.btn.btn-info.mx-2{ href: edit_project_path(@project) } Edit
        = button_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  %div.card-body
    %p.card-text= @project.description
    = render 'tasks/task_list'
  %div.card-footer.d-flex.justify-content-between
    %a.btn.btn-primary{ href: projects_path } Back
    %a.btn.btn-success{ href: new_project_task_path(@project) } Add New Task

app/views/tasks/_form.html.haml
= simple_form_for [@project, @task], html: { class: 'needs-validation', multipart: true } do |f|
    .form-group
        = f.input :subject, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
    .form-group
        = f.input :description, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
    - if @task.persisted?
        .form-group
            = f.input :status, collection: Task.statuses.keys, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
    .form-group
        = f.input :user_id, collection: User.all.map { |u| [u.full_name, u.id] }, label: "Assign to", input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
    %h3 Attachments
    .form-group
        = f.simple_fields_for :attachments do |a|
            .form-group
                = a.input :description, input_html: { class: 'form-control' }, label: "Attachment description"
            .form-group
                = a.input :upload, as: :file, input_html: { class: 'form-control-file' }, label: false
    .form-group
        = f.button :submit, class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
%h3 Tasks

%table.table
  %thead
    %tr
      %th Subject
      %th Status
      %th Resolving User
      %th Actions
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to "#{task.subject}", project_task_path(@project, task)
        %td= task.status
        %td= User.find(task.user_id).full_name
        %td.d-flex
          %a.btn.btn-primary.mr-2{ href: edit_project_task_path(@project, task) } Edit
          = button_to 'Delete', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

= paginate @tasks

app/views/tasks/edit.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1 Edit Task
      %a.btn.btn-primary{ href: project_path(@project) } Back
  %div.card-body
    = render 'form'

app/views/tasks/new.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1 Add a new task
      %a.btn.btn-primary{ href: project_path(@project) } Back
  %div.card-body
    = render 'form'

app/views/tasks/show.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between
      %h5= @task.subject
      %div.d-flex
        %a.btn.btn-info.mx-2{ href: edit_project_task_path(@project, @task) } Edit
        = button_to 'Delete', project_task_path(@project, @task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  %div.card-body
    %h6 Description
    %p.card-text= @task.description
    %h6 Attachments
    %ul.list-group
      - @task.attachments.each do |attachment|
        %li.list-group-item.d-flex.justify-content-between.align-items-center
          = attachment.description
          = link_to 'Download', attachment.upload.url, class: 'btn btn-outline-primary btn-sm' if attachment.upload.present?
  %div.card-footer
    %a.btn.btn-primary{ href: project_path(@project) } Back

app/views/users/_form.html.haml
= simple_form_for @user, html: { class: 'needs-validation', multipart: true } do |f|
  .form-group
    = f.input :avatar, as: :file, input_html: { class: 'form-control-file' }, label: 'Avatar'
  .form-group
    = f.input :first_name, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.input :last_name, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.input :address, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.input :email, required: true, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.input :password, input_html: { class: 'form-control' }, label_html: { class: 'form-label' }
  .form-group
    = f.button :submit, class: 'btn btn-primary'

app/views/users/edit.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1 Edit User
      %a.btn.btn-primary{ href: users_path } Back
  %div.card-body
    = render 'form'

app/views/users/index.html.haml
%div.card.mx-5
  %div.card-header
    %h1 Users
  %div.card-body
    %table.table.table-md
      %thead
        %tr
          %th Full Name
          %th Email
          %th Actions
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.full_name, user_path(user)
            %td= user.email
            %td.d-flex
              %a.btn.btn-primary.mr-2{ href: edit_user_path(user) } Edit
              = button_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

    - if @users.total_pages > 1
      .pagination
        = paginate @users

  %div.card-footer
    %div.d-flex.justify-content-between
      %a.btn.btn-primary{ href: root_path } Back
      %a.btn.btn-success{ href: new_user_path } Add New User

app/views/users/new.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between.align-items-center
      %h1 Add New User
      %a.btn.btn-primary{ href: users_path } Back
  %div.card-body
    = render 'form'

app/views/users/show.html.haml
%div.card.mx-5
  %div.card-header
    %div.d-flex.justify-content-between
      %h4= @user.full_name
      %div.d-flex
        %a.btn.btn-info.mx-2{ href: edit_user_path(@user) } Edit
        = button_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  %div.card-body
    %div.d-flex.flex-column.align-items-start
      %div
        %strong Avatar:
        - if @user.avatar?
          = image_tag(@user.avatar.url, size: "100x100", class: 'ml-2')
      %div.mt-2
        %strong First Name:
        %span.ml-2= @user.first_name
      %div.mt-2
        %strong Last Name:
        %span.ml-2= @user.last_name
      %div.mt-2
        %strong Email:
        %span.ml-2= @user.email
      %div.mt-2
        %strong Address:
        %span.ml-2= @user.address
  %div.card-footer
    %a.btn.btn-primary{ href: users_path } Back